{% set name = "inform" %}
{% set version = "1.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inform-{{ version }}.tar.gz
  sha256: c463106e1b14b8719e168ec39d0efd736d2be082edc46e1f59f95fdc6d02f2b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - arrow
    - six

test:
  imports:
    - inform
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/KenKundert/inform
  summary: print & logging utilities for communicating with user
  description: |
    A package that provides specialized print functions that are used when
    communicating with the user. It allows you to easily print attractive,
    informative, and consistent error messages.
  license: MIT
  license_file: LICENSE
  doc_url: https://inform.readthedocs.io
  dev_url: https://github.com/KenKundert/inform

extra:
  recipe-maintainers:
    - KenKundert
