{% set name = "inform" %}
{% set version = "1.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inform-{{ version }}.tar.gz
  sha256: 63c1d68565f8d1973cd32fc632b42857d38720baeed236196ba3391c8a907594

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.6
    - arrow
    - six

test:
  imports:
    - inform
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KenKundert/inform
  summary: print & logging utilities for communicating with user
  description: |
    A package that provides specialized print functions that are used when
    communicating with the user. It allows you to easily print attractive,
    informative, and consistent error messages.
  license: MIT
  license_file: LICENSE
  doc_url: https://inform.readthedocs.io
  dev_url: https://github.com/KenKundert/inform

extra:
  recipe-maintainers:
    - KenKundert
