{% set name = "inform" %}
{% set version = "1.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inform-{{ version }}.tar.gz
  sha256: 9a5808ca048b0b76dad25f3ce2676c734b4e1628e7ea4cdc3a8add69b91a137a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.6
    - arrow
    - six

test:
  imports:
    - inform
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KenKundert/inform
  summary: print & logging utilities for communicating with user
  description: |
    A package that provides specialized print functions that are used when
    communicating with the user. It allows you to easily print attractive,
    informative, and consistent error messages.
  license: MIT
  license_file: LICENSE
  doc_url: https://inform.readthedocs.io
  dev_url: https://github.com/KenKundert/inform

extra:
  recipe-maintainers:
    - KenKundert
